### ISSUE TITLE
after i input the keystore password ,it's always staying at that moment

### ISSUE THREAD

**Issue by OK0X** [ethereum/eth2.0-deposit-cli#42] opened 2020-06-23 02:15 UTC
`Administrator@BlockStar-Desk MINGW64 ~/eth2.0-deposit-cli (master)
$ sh deposit.sh --num_validators=1 --mnemonic_language=english
msys
Running deposit-cli...
Type the password that secures your validator keystore(s): 1qaZsdfg4398?
`
when i have input password , it stay there forever,

**Comment by hwwhww** [comment] 2020-06-23 08:27
@OK0X Hi!

1. What's your Python version? Run:
```sh
python --version
```

2. Could you try the following command, see if this testing script works with your env?
```sh
python -m pip install -r requirements_test.txt
python ./test_deposit_script.py
```

**Comment by OK0X** [comment] 2020-06-24 01:09
1.C:\Users\Administrator\eth2.0-deposit-cli>python --version
Python 3.7.3
2.python -m pip install -r requirements_test.txt
![image](https://user-images.githubusercontent.com/48879766/85484704-f4fe1d80-b5f9-11ea-938d-c14e6525a74c.png)
![image](https://user-images.githubusercontent.com/48879766/85484927-57efb480-b5fa-11ea-8301-b4b0c5f029d2.png)

**Comment by hwwhww** [comment] 2020-06-25 03:34
Hmm, it looks like the test script works for you (succeeded with the 🦏 )

Could you share the screenshot of the issue of hanging on password input?

**Comment by OK0X** [comment] 2020-06-28 00:23
of course yes. 
![Snipaste_2020-06-28_08-22-45](https://user-images.githubusercontent.com/48879766/85934661-a661c380-b918-11ea-8de1-c4b7acba5d43.jpg)
it is hanging here

**Comment by fsiatama** [comment] 2020-07-28 15:28
Yes, I have the same problem

**Comment by hwwhww** [comment] 2020-10-20 17:12
@OK0X @fsiatama 
Sorry, I still have no idea how to reproduce it... Do you mind trying [binary](https://github.com/ethereum/eth2.0-deposit-cli/#option-1-download-binary-executable-file-1) or [virtualenv](https://github.com/ethereum/eth2.0-deposit-cli/#option-3-build-deposit-cli-with-virtualenv-1)?

**Comment by hwwhww** [comment] 2020-10-20 17:24
closing it now. Let me know if the above suggestions don't work for you.

**Closed by hwwhww** 2020-10-20 17:24 UTC
